on:
  push:
    branches: [main, master, test_github]
  pull_request:
    branches: [main, master]

name: test

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
    steps:
      - uses: actions/checkout@v2
      - name: Install R
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y r-base
      - uses: jeremyirilli/swi-prolog-pack-cover@main
