on:
  push:
    branches: [main, master, test_github]
  pull_request:
    branches: [main, master]

name: test
 
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
    steps:
      - uses: actions/checkout@v2
      - name: Install R
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y r-base
          mkdir -p $HOME/Rlibs 
          R -e "install.packages('RInside', lib='$HOME/Rlibs'); install.packages('Rcpp', lib='$HOME/Rlibs')"
          echo "R_LIBS=$HOME/Rlibs" >> ~/.Renviron
          R -e "library(RInside); library(Rcpp)"
          echo "R_LIBS_USER=$HOME/Rlibs" >> $GITHUB_ENV

      - name: Install SWI-Prolog on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-add-repository ppa:swi-prolog/devel
          sudo apt-get update
          sudo apt-get install swi-prolog
        shell: bash

      - name: Check installation
        run: swipl -t check_installation
        shell: bash

      - name: Install rologp
        run: |
          export R_LIBS_USER=$HOME/Rlibs
          swipl -t "pack_install(rologp, [interactive(false)])"
        shell: bash

      - name: Move rologpp.so to foreign directory
        run: |
          mkdir -p ~/.local/share/swi-prolog/pack/rologpp/foreign
          cp ~/.local/share/swi-prolog/pack/rologpp/lib/x86_64-linux/rologpp.so ~/.local/share/swi-prolog/pack/rologpp/foreign/
          ls ~/.local/share/swi-prolog/pack/rologpp/foreign

      - name: Install pack
        run: |
          export R_LIBS_USER=$HOME/Rlibs
          PACK_DIR="$HOME/.local/share/swi-prolog/pack/interval"
          if [ -d "$PACK_DIR" ]; then
            echo "Pack directory exists: $PACK_DIR"
            echo "Removing existing pack directory..."
            rm -rf "$PACK_DIR"
          else
            echo "Pack directory does not exist: $PACK_DIR"
          fi
          REPO_URL="https://github.com/$GITHUB_REPOSITORY.git"
          echo "Repository URL: $REPO_URL"
          swipl -t "pack_install('$REPO_URL', [interactive(false), link(false)])"
        shell: bash
      
      #- name: Run tests
      #run: |
      #  swipl -s "${{ github.workspace }}/action.pl"
      #shell: bash
      
      #- uses: jeremyirilli/swi-prolog-pack-cover@main
