on:
  push:
    branches: [main, master, test_github]
  pull_request:
    branches: [main, master]

name: test
 


jobs:
  run-tests:
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
    steps:
      - uses: actions/checkout@v2
      - name: Install R
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y r-base
          mkdir -p $HOME/Rlibs 
          R -e "install.packages('RInside', lib='$HOME/Rlibs')"
          R -e "install.packages('Rcpp', lib='$HOME/Rlibs')"
          echo "R_LIBS=$HOME/Rlibs" >> ~/.Renviron
          R -e "library(RInside)"
          R -e "library(Rcpp)"
          echo "R_LIBS_USER=$HOME/Rlibs" >> $GITHUB_ENV
      - uses: jeremyirilli/swi-prolog-pack-cover@main
